# fly.toml app configuration file generated for vault-service on 2025-06-28T23:41:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vault-service'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8200
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "vault_data"
  destination = "/vault/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
